# Site settings
title: Sam Haslam
email: samhaslam87@gmail.com
url: https://masmalsah.github.io
description: "A web, graphic and multimedia portfolio for freelance digital designer, Samuel Haslam"
keywords: "Samuel Haslam, UI, user interface deigner, portfolio, advertising, design, graphics, branding, photoshop, graphic design, graphic designer, logo design, web, internet, layout, websites, website design, web design, website designer, graphic art"
skills: "User Interface Design - User Experience Design - Art Direction - Graphic Design"
meta_author: Haslam Samuel

# Google webmaster tools
google_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000000 #80B3FF
  primary-rgb: "145,18,1" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: masmalsah
  social: Profiles

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sam-haslam-4440003a

# Build settings
markdown: kramdown
permalink: pretty
