# Site settings
title: Sam Haslam
email: samhaslam87@gmail.com
url: https://samhaslam.design
description: "A web, graphic and multimedia portfolio for freelance digital designer, Samuel Haslam"
keywords: "Samuel Haslam, UI, user interface deigner, portfolio, advertising, design, graphics, branding, photoshop, graphic design, graphic designer, logo design, web, internet, layout, websites, website design, web design, website designer, graphic art"
skills: "User Interface Design - User Experience Design - Art Direction - Graphic Design"
meta_author: Haslam Samuel

# Google webmaster tools
google_verify:

collections:
  case_studies:
  previous_works:

sass:
  style: compressed
  sass_dir: _sass

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

  
# Footer settings
footer:
  copyright: masmalsah
  social: Profiles

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sam-haslam-4440003a

# Build settings
markdown: kramdown
permalink: pretty
