# Site settings
title: Samuel Haslam
email: samhaslam87@gmail.com
url: https://masmalsah.github.io
description: "A web, graphic and multimedia portfolio for freelance digital designer, Samuel Haslam"
keywords: "Samuel Haslam, UI, user interface deigner, portfolio, advertising, design, graphics, branding, photoshop, graphic design, graphic designer, logo design, web, internet, layout, websites, website design, web design, website designer, flash, flashs, flash animation, flash design, flash animator, flash designer, art, graphic art"
skills: "User Experience Designer - Graphic Artist - Front End Developer"
meta_author: Haslam Samuel

# Google webmaster tools
google_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: masmalsah
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
